using System;

namespace TimHanewich.Foundry.OpenAI.Responses
{
    public enum Role
    {
        developer = 0,      // developer messages are instructions provided by the application developer, prioritized ahead of user messages.
        user = 1,           // user messages are instructions provided by an end user, prioritized behind developer messages.
        assistant = 2       // Messages generated by the model have the assistant role.
    }
}